[project]
name = "baby-lights"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kivy>=2.3.1,<3.0.0",
    "kivy-reloader>=0.7.0",
]

[project.scripts]
baby-lights = "baby_lights:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["baby_lights*"]
exclude = ["tests*"]

[tool.setuptools.package-data]
baby_lights = ["**/*.kv", "assets/*.png"]

[tool.ruff]
line-length = 88
extend-exclude = ['.venv']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.mypy]
python_version = "3.13"
strict = false
ignore_missing_imports = true
# Disable missing type annotation warnings
disallow_untyped_defs = false
disallow_incomplete_defs = false
disallow_untyped_calls = false
warn_return_any = false

[tool.uv.sources]
kivy-reloader = { git = "https://github.com/kivy-school/kivy-reloader", branch = "main" }
ksp-bootstraps = { git = "https://github.com/kivy-school/ksp-bootstraps", branch = "master" }

[dependency-groups]
dev = [
    "kivy-reloader[desktop]>=0.7.0",
    "ksp-bootstraps",
    "ksproject",
    "mypy>=1.17.1",
]

[tool.uv]
index-strategy = "unsafe-best-match"
find-links = ["./wheelhouse"]

[tool.uv.pip]
extra-index-url = [
    "https://pypi-index.psychowaspx.workers.dev/simple",
    "https://pypi.anaconda.org/kivyschool/simple"
]
find-links = ["./wheelhouse"]

#### kivy-school configuration ####

[tool.kivy-school]
app_name = "Baby Lights"
bootstrap = "kivy"

[tool.kivy-school.android]
package_name = "com.kivyschool.baby_lights"
version_name = "0.1.1"

# version_name = "0.1" # change when you want to release a very new version
version_code = 2 # increase for each Play Store update

icon = "baby_lights/assets/icon.png"
presplash = "baby_lights/assets/presplash.png"
presplash_color = "#000000"

# icon = "relative to pyproject (png)"
# presplash_color = "#FFFFFF"
# presplash = "relative to pyproject (png,jpg,gif)"
# presplash_lottie = "relative to pyproject (json)"

archs = [
    "arm64-v8a",
    # "x86_64" # Uncomment if you want to support x86_64 (emulators), but it will increase APK size
]
gradle_dependencies = [
    # "com.onesignal:OneSignal:[5.6.1, 5.9.99]" # Example of adding OneSignal for push notifications; adjust version as needed
]
gradle_plugins = [
    # 'id("com.google.gms.google-services") version "4.4.2" apply false'
]
permissions = ["INTERNET", "REQUEST_LOCK_TASK"]
post_build = "android_post_build.py"

api = 36
min_api = 24
sdk = "36"
ndk = "28c"
ndk_api = 24

global_tools = true # Set to <false> to use project-local SDK/NDK (./.kivyschool); set to <true> to use shared/global versions (~/.kivyschool or global_tools_path)
#global_tools_path = "~/.kivyschool" # Override root path when global_tools = true; ignored when global_tools = false

# sdk_path = "/path/to/android-sdk"
# ndk_path = "/path/to/android-ndk"
# java_path = "/path/to/jdk"

# # Format 1: Flat list (Destination, Source 1, Source 2)
# include_files = [
#     ["gradle/app", "./google-services.json", "./some-other-config.xml"]
# ]

# # Format 2: Nested list (Destination, [Source 1, Source 2])
# include_files = [
#     ["gradle/app", ["./google-services.json", "./some-other-config.xml"]]
# ]

# pre_build = "path/to/android_prebuild.py"
# post_build = "path/to/android_prebuild.py"

byte_compile_python = true

# <meta-data> entries inside <application>
# [tool.kivy-school.android.meta_data]
# "com.google.android.gms.ads.APPLICATION_ID" = "ca-app-pub-xxxxxxxx~xxxxxxxx"

# --- Services ---
# [[tool.kivy-school.android.services]]
# name = "MyService1"
# start_type = "START_NOT_STICKY"
# entrypoint = "hello_world.services.myservice1"
# foreground = true
# foreground_service_type = "location|dataSync"
# notification_title = "MyService1 Running"
# notification_text = "Service is managing background data."
# notification_icon = "stat_notify_sync"

[tool.kivy-school.ios]
bundle_id = "org.example.baby_lights"
minimum_deployment = "15.6"
info_plist = {}
entitlements = {}
permissions = []
frameworks = []
#developer_team = "ABC123XYZ" # Set to your Apple Developer Team ID (e.g. ABC123XYZ) to enable automatic code signing; leave as null for manual signing
# pre_build = "path/to/ios_prebuild.py"
# post_build = "path/to/ios_postbuild.py"

[tool.kivy-school.macos]
bundle_id = "org.example.baby_lights"
minimum_deployment = "11.5"
info_plist = {}
entitlements = {}
#developer_team = "ABC123XYZ" # Set to your Apple Developer Team ID (e.g. ABC123XYZ) to enable automatic code signing; leave as null for manual signing
# pre_build = "path/to/android_prebuild.py"
# post_build = "path/to/android_postbuild.py"
